# PVPCooldown plugin config

total-seconds: 20 # Duration of cooldown in seconds

text-bar: "PVP mode ends in %d seconds"
text-entered: "You entered PVP. Don't leave the server or you will die"
text-quit: "You quit PVP"
text-on-command: "You can not use commands during PVP"